# Generated by Django 6.0.7 on 2026-08-16 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_alter_order_order_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='address_type',
            field=models.CharField(choices=[('hm', 'Home'), ('wk', 'Work'), ('pp', 'Pickup point')], default='hm', max_length=2, verbose_name='Address Type'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customer',
            name='customer_type',
            field=models.CharField(choices=[('nw', 'New'), ('rg', 'Regular'), ('vp', 'VIP'), ('wh', 'Wholesale')], default='nw', max_length=2, verbose_name='Customer Type'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pn', 'Pending'), ('pd', 'Paid'), ('pr', 'Processing'), ('sh', 'Shipped'), ('dl', 'Delivered'), ('cl', 'Cancelled')], default='av', max_length=2, verbose_name='Status'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='status',
            field=models.CharField(choices=[('is', 'In stock'), ('od', 'On demand'), ('aw', 'Awaited'), ('dc', 'Discontinued'), ('rm', 'Removed from sale')], default='is', max_length=2, verbose_name='Status'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='productdetail',
            name='status',
            field=models.CharField(choices=[('cp', 'Compact'), ('bk', 'Bulky')], default='cp', max_length=2, verbose_name='Status'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='supplier',
            name='status',
            field=models.CharField(choices=[('av', 'Active'), ('sp', 'Suspended'), ('bl', 'Blacklisted')], default='pn', max_length=2, verbose_name='Status'),
            preserve_default=False,
        ),
    ]
