# Generated by Django 6.0.7 on 2026-08-16 15:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_address_address_type_customer_customer_type_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productdetail',
            old_name='status',
            new_name='pd_type',
        ),
    ]
