# Generated by Django 6.0.7 on 2026-08-17 15:50

import django_extensions.db.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_rename_status_productdetail_pd_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='slug',
            field=django_extensions.db.fields.AutoSlugField(blank=True, editable=False, populate_from='name'),
        ),
        migrations.AlterField(
            model_name='productdetail',
            name='pd_type',
            field=models.CharField(choices=[('cp', 'Compact'), ('bk', 'Bulky')], max_length=2, verbose_name='Type'),
        ),
    ]
